------创建分支
$ git checkout -b develop-tangang;
$ git branch develop-tangang;


------切换分支
$ git checkout develop-tangang;

------远程推送分支
$ git push origin develop-tangang:develop-tangang;

------删除远程分支 origin后必须有空格
$ git push origin :develop-tangang;

-----切换到本地其它分支
$ git checkout develop;

------删除本地对应分支（需要切换到其它分支）
$ git branch -d develop-tangang;

---回滚指定文件
$ cd 到文件位置
 
-----查询日志
$ git log com.meyacom.crm-context.properties
commit 36ef4cbe1267dfebd89faef86442c7d488a03a5a (HEAD -> develop-tangang)
Author: tang <tang@meyacom.com>
Date:   Mon Sep 4 13:56:37 2017 +0800

    OPS-77 天安FTP数据回写数据修改20170904

commit b3df261933f6f6913eab6c53b0a084cb3c5f6d86
Author: zhangfeng <zhangfeng@jkjingji.com>
Date:   Mon Aug 28 17:47:50 2017 +0800

    ydzy

-----回滚指定文件-版本
$ git reset b3df261933f6f6913eab6c53b0a084cb3c5f6d86 com.meyacom.crm-context.pr
operties
Unstaged changes after reset:
M       com.meyacom.crm/com.meyacom.crm-intf/src/main/resources/com.meyacom.crm-
context.properties

-----提交到本地参考
$ git commit -m "revert old file because yjl commmit have a bug";
[develop-tangang e167979] revert old file because yjl commmit have a bug
 1 file changed, 4 insertions(+), 9 deletions(-)

wukh@tangang MINGW64 /e/work/gitworkspace/ydzy/com.meyacom.crm/com.meyacom.crm-i
ntf/src/main/resources (develop-tangang)

-----更新到工作目录
$ git checkout com.meyacom.crm-context.properties

-----提交到远程仓库
$ git push origin develop


------相当于是从远程获取最新版本到本地，不会自动merge,在实际使用中，git fetch更安全一些,因为在merge前，我们可以查看更新情况，然后再决定是否合并
git fetch origin develop:develop
git diff develop 
git merge develop

--相当于是从远程获取最新版本并merge到本地
git pull origin develop

